tab_empty = sprintf('%s\n',...
"General 6R                         &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f & ABB YUMI, fixed \\(q_3\\) \\\\", ...
"Two intersecting axes              &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f & RRC K-1207i, fixed \\(q_6\\)\\\\", ...
"Spherical wrist                    &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f & Spherical-Bot\\\\", ...
"\\qquad and two intersecting axes   &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f & KUKA LBR iiwa 7 R800, fixed \\(q_3\\)\\\\", ...
"\\qquad and two parallel axes       &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f & ABB IRB 6640\\\\", ...
"Three parallel axes                &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f & Three-Parallel-Bot\\\\", ...
"\\qquad and two intersecting axes   &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f & UR5\\\\");

sprintf(tab_empty,...
1e6*mean(runtimes_gen_6_dof_m),                   1e6*std(runtimes_gen_6_dof_m),                    1e6*mean(runtimes_gen_6_dof),                    1e6*std(runtimes_gen_6_dof),                    1e6*mean(runtimes_yumi),               1e6*std(runtimes_yumi),...
1e6*mean(runtimes_IK_2_intersecting_m),           1e6*std(runtimes_IK_2_intersecting_m),            1e6*mean(runtimes_IK_2_intersecting),            1e6*std(runtimes_IK_2_intersecting),            1e6*mean(runtimes_RRC),                1e6*std(runtimes_RRC),...
1e6*mean(runtimes_IK_spherical_m),                1e6*std(runtimes_IK_spherical_m),                 1e6*mean(runtimes_IK_spherical),                 1e6*std(runtimes_IK_spherical),                 1e6*mean(runtimes_spherical_bot),      1e6*std(runtimes_spherical_bot),...
1e6*mean(runtimes_IK_spherical_2_intersecting_m), 1e6*std(runtimes_IK_spherical_2_intersecting_m),  1e6*mean(runtimes_IK_spherical_2_intersecting),  1e6*std(runtimes_IK_spherical_2_intersecting),  1e6*mean(runtimes_KUKA),               1e6*std(runtimes_KUKA),...
1e6*mean(runtimes_IK_spherical_2_parallel_m),     1e6*std(runtimes_IK_spherical_2_parallel_m),      1e6*mean(runtimes_IK_spherical_2_parallel),      1e6*std(runtimes_IK_spherical_2_parallel),      1e6*mean(runtimes_IRB_6640),           1e6*std(runtimes_IRB_6640),...
1e6*mean(runtimes_IK_3_parallel_m),               1e6*std(runtimes_IK_3_parallel_m),                1e6*mean(runtimes_IK_3_parallel),                1e6*std(runtimes_IK_3_parallel),                1e6*mean(runtimes_three_parallel_bot), 1e6*std(runtimes_three_parallel_bot),...
1e6*mean(runtimes_IK_3_parallel_2_intersecting_m),1e6*std(runtimes_IK_3_parallel_2_intersecting_m), 1e6*mean(runtimes_IK_3_parallel_2_intersecting), 1e6*std(runtimes_IK_3_parallel_2_intersecting), 1e6*mean(runtimes_ur5),                1e6*std(runtimes_ur5))

%%

tab_empty = sprintf('%s\n',...
"1:& Cone and point    &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f \\\\", ...
"2:& Two cones         &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f \\\\", ...
"2E:& Two offset cones &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f \\\\", ...
"3:& Cone and sphere   &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f \\\\", ...
"4:& Cone and plane    &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f \\\\", ...
"5:& Three cones       &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f \\\\", ...
"6:& Four cones        &%5.0f &$\\pm$& %5.2f &%5.0f &$\\pm$& %5.2f \\\\");


sprintf(tab_empty,...
1e6*mean(runtimes_sp1), 1e6*std(runtimes_sp1), 1e6*mean(runtimes_sp1_mex), 1e6*std(runtimes_sp1_mex), ...
1e6*mean(runtimes_sp2), 1e6*std(runtimes_sp2), 1e6*mean(runtimes_sp2_mex), 1e6*std(runtimes_sp2_mex),...
1e6*mean(runtimes_sp2E),1e6*std(runtimes_sp2E),1e6*mean(runtimes_sp2E_mex),1e6*std(runtimes_sp2E_mex),...
1e6*mean(runtimes_sp3), 1e6*std(runtimes_sp3), 1e6*mean(runtimes_sp3_mex), 1e6*std(runtimes_sp3_mex),...
1e6*mean(runtimes_sp4), 1e6*std(runtimes_sp4), 1e6*mean(runtimes_sp4_mex), 1e6*std(runtimes_sp4_mex),...
1e6*mean(runtimes_sp5), 1e6*std(runtimes_sp5), 1e6*mean(runtimes_sp5_mex), 1e6*std(runtimes_sp5_mex),...
1e6*mean(runtimes_sp6), 1e6*std(runtimes_sp6), 1e6*mean(runtimes_sp6_mex), 1e6*std(runtimes_sp6_mex))